### ISSUE TITLE
Screen identification

### ISSUE THREAD

**Issue by Fullmono** [andrei-tatar/imagotag-hack#1]
Hi, 

I'm really interested in your project. I'm wondering how did you identify the screen manufacturer and reference? 
I own an imagotag with a 2.9 screen which looks like a GDEW029Z10 from good display. But the screen doesn't work with code provided as an example by the manufacturer. (It displays an image but this an is offset). I have tried all the codes for the 2.9" screens from Good Display. That's the reason why I question the screen reference...

Thank you for your help

**Comment by andrei-tatar** [comment]
Hi,
First, I reversed the pinout from the board (VCC, GND, signal wires, NC)
After that I searched available eink screens that matched the pinout and the sizes I had.

Maybe the offset can be fixed from the software driver.

**Comment by Loryuwu** [comment]
@Fullmono Hi, I have one of those displays from the company "Pervasive Displays," and no matter how much I searched for the codes and batch number, Google didn't show any results. Maybe that's your case too?

**Comment by skiphansen** [comment]
@Loryuwu If the display is connected to the controller using a connector then you might consider hooking it up to a breakout board and an Arduino and then trying this project https://github.com/bitbank2/bb_epaper .  He has a display tester example that supports a huge number of displays.  The ePaper display pinouts are pretty standard and there are only a few manufactures of the display controller chips that are used internally by the ePaper display manufactures.  Most that I've run across are from UltraChip or Solomon Systeh.

This repo https://github.com/CursedHardware/epd-driver-ic has a huge number of datasheets from various companies that's VERY useful.

You can find a GREAT writeup on hacking price labels here: https://dmitry.gr/?r=05.Projects&proj=29.%20eInk%20Price%20Tags

Good luck!

**Comment by Loryuwu** [comment]
@skiphansen 
Thanks for the reply!
My current issue isn’t the display; I’ve got that part fully under control. My ESL uses a Pervasive Displays panel and, since they provide their own libraries, I was able to develop in my repository [[link]](https://github.com/Loryuwu/CC2510-ESL?tab=readme-ov-file) a dedicated module compatible with three sizes (2.13”, 2.66” and 4.17”), all of them three-color (BWR) displays.

What’s blocking me now is the controller chip itself. I haven’t been able to get the RF communication working, and I also want to implement a module to handle communication with the external memory over SPI and with the NFC chip over I²C—though I haven’t even started that part yet. For the moment, I’m completely stuck on the RF side.

**Comment by skiphansen** [comment]
Take a look at Ti's "SmartRF Studio".  With 2 debuggers and two connected boards you can play with RF communications between the two boards w/o writing any code.   Figuring out how to configure the radio is usually the hardest part.  An TI eval board would be helpful, sometimes they are quite cheap.

I haven't used the CC2510 personally, but I've done a lot of work with the CC1110 which is similar, but for SubGhz rather than 2.5Ghz.

**Comment by Loryuwu** [comment]
Unfortunately, I don’t have a second debugger yet, and it’s unlikely that I’ll be able to get one anytime soon, even though I would really like to try that experiment.

For now, my workaround for not having two debuggers was to try setting one of the ESLs to send a packet in a loop, and then use the debugger together with another ESL to play around with SmartRF Studio and try to capture those packets. I’m not sure how well it will work, but it’s the only approach I can think of at the moment.
